### PR TITLE
Update react-auth.mdx

### PR DESCRIPTION
**Pull request by bmwasonga**
modified the privateRoute to fix some errors that I faced wile working with it.

### CODE REVIEW

**Comment by elitan** [comment]
I think actually this should be enough:

```jsx
export function AuthGuard(props: any) {
  const { signedIn } = useAuth();

  if (signedIn === null) {
    return <div>Loading...</div>;
  }

  if (!signedIn) {
    return <Redirect to="/login" />;
  }

  // user is logged in
  return props.children;
}
```

**Comment by elitan** [comment]
@bmwasonga Could you test the code above with your react project? And maybe we could edit it to this instead?

**Comment by bmwasonga** [comment]
this is what I get. I am using Next Js
next

**Comment by elitan** [comment]
That's strange. Could this be because of different React versions? What react versions do you use for this project @bmwasonga ?

**Comment by bmwasonga** [comment]
react

**Comment by guicurcio** [comment]
Try writing `privateRoute.jsx` rather than the `.js` extension since some static analysis tools can't recognize you're working with react.

**Pull request closed without merging**
